#!/bin/sh

# Core extensions
alias ll='ls -lhFG'
alias vi='vim'
alias rm='/bin/rm -i'
alias cp='/bin/cp -i'
alias mv='/bin/mv -i'
alias ls='ls -FG'
alias rrm='/bin/rm -rf'

# Git aliases
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit -v"
alias gd="git diff"
alias gl="git log"
alias gpr="git pull --rebase"
alias gca="git commit --amend"
alias chead="git commit --amend -CHEAD"

# Utilities
alias stamp="date +'%Y_%m_%d_%H%M%S'"
